### ISSUE TITLE
concurrency problems?

### ISSUE THREAD

**Issue by samzilverberg** [springernature/bandiera#102]
making "sequential" requests to the bandiera server works fine, but when makine a couple in parallel some scary errors come up, such as `message type 0x54 arrived from server while idle` and more.

### to reproduce:

- start bandiera locally (docker/non docker doesnt matter) per readme instructions
- db can be empty
- via bash: `for i in {1..5}; do http http://127.0.0.1:5000/api/v2/all & done`
and viola should see some nasty errors.

sequential calling the api works fine:  
`for i in {1..5}; do http http://127.0.0.1:5000/api/v2/all ; done`

note: i'm using httpie, your'e welcome to use curl for same results :)

### what i already tried
i was able to reproduce this:
- using postgres and mysql as db (so not strictly db related)
- with/without feature caching:
  - turned off caching by changing `web_app_base.rb` line 19 to  
```set :feature_service , FeatureService.new(audit_log)```

### more ideas:
might be puma prob, maybe even just configuration related.
i'm not familiar enough with ruby based web servers so didn't try changing this yet.

**Comment by dazoakley** [comment]
Hi @samzilverberg,

This is just the default puma config - it's not set up for production workloads.  You need to tune the amount of workers/processes and threads that you'd like puma to consume.  This can be done via environment variables as you start the server (https://github.com/springernature/bandiera/blob/master/config/puma.rb#L10).

From memory, while I was at SpringerNature we had it running with 5 processes, and 16 threads minimum, 64, maximum.  Between the two servers (behind a load balancer) they were taking about 1,000,000 requests a day without any issues.

Hope that helps. :)

For more information about configuring puma check out the project readme. https://github.com/puma/puma#configuration

**Comment by dazoakley** [comment]
Sorry for the slow response - it was a bank holiday weekend here in the UK so I've not been near email/github. :)
